PowerShell/PSSwagger

- PSSwagger/SwaggerUtils.psm1
Pluralization is only supported for the English language. Importing PSSwagger fails on non-English systems - this fix enables the Pluralization service to be used on English and non-English systems.
```
Ausnahme beim Aufrufen von "CreateService" mit 1 Argument(en):  "Die Kultur "Deutsch (Deutschland)" wird nicht unterstützt. Die Pluralisierung wird derzeit
nur für die englische Sprache unterstützt."
In Zeile:1 Zeichen:1
+ [System.Data.Entity.Design.PluralizationServices.PluralizationService ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NotImplementedException
```
> Fix localization error in SwaggerUtils

- PSSwagger/SwaggerUtils.psm1
Below $oDataQuery expression is not getting generated for the swagger operations with x-ms-odata when $Filter global parameter is also referenced in other swagger operations without  x-ms-odata extension.
This is happening as we were not cloning the global parameter details when copying for the swagger operations.
```powershell
$oDataQuery = ""
if ($Filter) { $oDataQuery += "&`$Filter=$Filter" }
$oDataQuery = $oDataQuery.Trim("&")    
```
Note: I have created a tracking issue for adding tests for x-ms-odata extension #306
> Ensure $oDataQuery expression is generated properly with global parameters

- PSSwagger/PSSwaggerUtility/PSSwaggerUtility.psm1
Removed the langversion from CSC parameters as latest is the default language version.
**Reason**: '/langversion:latest' is not supported on all versions of CSC.exe, especially the version installed with Visual Studio.
> Remove '/langversion' from CSC.exe parameter list as 'latest' is the default language version

- PSSwagger/GeneratedHelpers.ps1
- PSSwagger/New-ServiceClient.ps1
- PSSwagger/PSSwagger.Constants.ps1
- PSSwagger/PSSwagger.psm1
- PSSwagger/Paths.psm1
- PSSwagger/SwaggerUtils.psm1
- README.md
- docs/testing/NewServiceClient.md
> Add New-ServiceClient utility function in generated module to enable mock testing

- PSSwagger/PSSwagger.Constants.ps1
- PSSwagger/PSSwagger.psm1
- Tests/PSSwaggerScenario.Tests.ps1
- Tests/TestUtilities.psm1
- Tests/run-tests.ps1
Write exceptions in generated commands + some fixes for core CLR test pass.
> Write exceptions in generated commands

- PSSwagger/PSSwagger.Constants.ps1
- PSSwagger/SwaggerUtils.psm1
- Updated the taskresult handling logic to give priority to the $taskResult.Result.Body. Resolves #319.
- Couple of other minor fixes found while generating modules for the Azure Swagger specs.
> Update the taskresult handling logic to give priority to the $taskResult.Result.Body

- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.ConsoleServer/CloudErrorTransform.json
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.ConsoleServer/PSSwagger.LTF.ConsoleServer.csproj
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.ConsoleServer/Program.cs
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.ConsoleServer/config.json
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.IO.Lib/PSSwagger.LTF.IO.Lib.csproj
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/LiveTestServer.cs
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/Messages/LiveTestError.cs
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/Messages/LiveTestRequest.cs
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/PSSwagger.LTF.Lib.csproj
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/Transforms/DynamicObjectTransform.cs
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/Transforms/DynamicObjectTransformDefinition.cs
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/vs-csproj/PSSwagger.LTF.Lib.csproj
Batch of fixes required to get error handling correct for the test server. At this point Azure Batch E2E tests pass.
- Update Newtonsoft.Json to 10.0.3 as 10.0.1 has a bug with respect to deserializing the ```CloudError``` type
- Unwrap expected exceptions into the final ```CloudError``` object - the framework provided is used for transforming any result, including other error types we might run into
- When returning an error response, include the last ```HttpResponseMessage```, if any. Remove the ```Content``` property as it's not serializable. However, sometimes the ```HttpResponseMessage``` is disposed so ```response.Content = null``` doesn't always work. To get around that issue, we manually create a clone.
- The error response schema in the library doesn't match the specification - …
> Handle error responses in Live Test Server

- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.IO.Lib/JsonRpcPipe.cs
- PSSwagger.LiveTestFramework/src/PSSwagger.LTF.Lib/LiveTestServer.cs
Think the problem is that sometimes the input stream isn't properly closed, and instead of not reading anything, the input stream reads the '\uffff' (65535) character continuously instead. This changes JsonRpcPipe to assume that when that character is read, input has stopped. The server now has a contract so that whenever an input pipe returns null message, the server stops.
I wasn't able to test this with the E2E tests because it creates Azure resources and running enough tests to get a repro might get expensive. Found the character issue using a different method, so this might not be the issue happening in the E2E tests.
Fixes #328
> Fix for server spinning bug

- PSSwagger/PSCommandVerbMap.ps1
- PSSwagger/PSSwagger.psm1
- PSSwagger/PSSwaggerUtility/PSSwaggerUtility.psm1
Changed warning level to 1 for generating assembly for Azure Swagger specs. Resolves below error.
```powershell
Generating module for 'C:\temp\AzureSwaggerSpecs\SwaggerSpecs\monitor\autoscale_API.json'.
PSSwaggerUtility\Add-PSSwaggerClientType : C:\temp\AzureSwaggerSpecs\AzModules\symbols\Azmonitor\0.0.1\Generated.Microsoft.PowerShell.Azmonitor.v001.cs(433,23): warning CS0108: 'ActivityLogAlertLeafCondition.Equals' hides inherited member 'object.
the new keyword if hiding was intended.
At C:\Code\PSSwagger\PSSwagger\PSSwagger.psm1:900 char:14
+ ...    if(-not (PSSwaggerUtility\Add-PSSwaggerClientType @AddPSSwaggerCli ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ …
```
> Change warninglevel to 1 for generating assembly for Azure Swagger specs

- PSSwagger/Paths.psm1
Fixed UnableToExtractDetailsFromSdkAssembly error when OperationType in OperationId conflicts with Definition name.
When OperationType value conflicts with a definition name, AutoREST generates method name by adding **Method** to the OperationType.
Current error for swagger specs of Azure Servicebus and Relay services.
```powershell
Generating module for 'C:\temp\AzureSwaggerSpecs\SwaggerSpecs\servicebus\servicebus.json'.
Update-PathFunctionDetails : Module generation failed. If no error messages follow, check the output of code metadata extraction above
Unable to find expected method 'CheckNameAvailabilityWithHttpMessagesAsync' on type 'Microsoft.PowerShell.Azservicebus.v001.INamespacesOperations'
At C:\Code\PSSwagger\PSSwagger\PSSwagger.psm1:555 char:28
+ ... onDetails = …
```
> Resolve error when OperationType in OperationId conflicts with Definition name

- PSSwagger.LiveTestFramework/build/PSSwagger.LiveTestFramework.Build.psm1
- PSSwagger.LiveTestFramework/test/PSSwagger.LiveTestFramework.Tests.psm1
- PSSwagger/PSSwaggerUtility/PSSwaggerUtility.psm1
- Tests/PSSwagger.Unit.Tests.ps1
As described in #333 $IsOSX was renamed to $IsMacOS. This pull request makes the necessary changes in PSSwagger.
> Rename IsOSX to IsMacOS after breaking change in PowerShell 6.0.0-beta.7 to fix #333

- PSSwagger/Definitions.psm1
- PSSwagger/SwaggerUtils.psm1
- Tests/PSSwaggerScenario.Tests.ps1
- Tests/data/ParameterTypes/ParameterTypesSpec.json
Added support for AdditionalProperties Json schema with array type.
```json
"type": "string",
"additionalProperties": {
"type": "array",
"items": {
"type": "string"
}
}
```
Current warning message for Azure Network service swagger spec.
```powershell
Generating module for 'C:\temp\AzureSwaggerSpecs\SwaggerSpecs\network\applicationGateway.json'.
WARNING: 'ParameterJsonObject' has unsupported properties.
type   additionalProperties                                                         description
----   --------------------                                                         -----------
string @{type=array; items=; description=List of IP Addresses within the tag (key)} Mapping of tags to list of IP Addresses included within the tag.
```
> Add support for AdditionalProperties Json schema with array type

- CHANGELOG.md
- PSSwagger/PSSwagger.psd1
- PSSwagger/PSSwaggerUtility/PSSwaggerUtility.psd1
- Added CHANGELOG.md
- Minor updates for releasing the 0.3.0 version of PSSwagger and PSSwaggerUtility modules
> Add CHANGELOG.md, and minor update for releasing 0.3.0 version

- PSSwagger/New-ServiceClient.ps1
When calling using custom host I get the error:
```
PSInvalidCastException: Cannot convert the "[scriptblock]::Create" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
ParameterBindingException: Cannot bind parameter 'ScriptBlock'. Cannot convert the "[scriptblock]::Create" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
at New-ServiceClient, C:\PS\Module\Azs.Gallery.Admin\0.1.0\New-ServiceClient.ps1: line 96
at Get-GalleryOperationList<Process>, C:\PS\Module\Azs.Gallery.Admin\0.1.0\Generated.PowerShell.Commands\SwaggerPathCommands\Get-GalleryOperationList.ps1: line 50
at <ScriptBlock>, C:\PS\Tests\src\Operation.Tests.ps1: line 56
```
Apparently the call
```
$Client.BaseUri = Invoke-Command -ScriptBlock …
```
> New-ServiceClient error on custom host

- PSSwagger/PSCommandVerbMap.ps1
Verb map change: 'Regenerate' to 'New' instead of 'Update' as per the feedback recieved from Azure PowerShell team.
> Verb map change: 'Regenerate' to 'New' instead of 'Update' 

- PSSwagger/Paths.psm1
- Tests/PSSwagger.Unit.Tests.ps1
Made changes to use separate PSCmdletOutputItemType variable for getting the output item type of pageable swagger operations.
Reason: $pageType is used in expanding the result script blocks for $skip and $top.
Refer: #342
> Use PSCmdletOutputItemType separate variable instead of pageType

- PSSwagger/PSSwagger.Resources.psd1
- PSSwagger/PSSwagger.psm1
- Tests/PSSwagger.Unit.Tests.ps1
> Escape '<#' and '#>', and replace '--' with '==' in Header content

- PSSwagger/PSSwagger.psm1
- Tests/PSSwaggerScenario.Tests.ps1
- Tests/TestUtilities.psm1
- docs/commands/New-PSSwaggerModule.md
Added -NoVersionFolder switch parameter on New-PSSwaggerModule cmdlet to not create the version folder
Resolves #353
> Add 'NoVersionFolder' switch on New-PSSwaggerModule to not create the version folder

- PSSwagger/Paths.psm1
- PSSwagger/SwaggerUtils.psm1
- Tests/PSSwaggerScenario.Tests.ps1
- Added support for generating the single Verb-Noun cmdlet with multuple parameter sets for OperationIds like Noun_Verb and Noun_VerbBySomething.
- Updated the parameterset prioritazation logic to retrieve the default parameter set with minimum number of mandatory parameters.
> Generate single Verb-Noun cmdlet for OperationIds like Noun_Verb and Noun_VerbBySomething

- CHANGELOG.md
- Removed the date next to the version as it requires additional commit when we need to release the newer versions at different date than the one mentioned in the changelog.md.
> Update change log to include the new changes into 0.3.0 release
